#!/bin/sh
#
# Automatically add branch name and branch description to every commit message except merge commit.
#

COMMIT_EDITMSG=$1

validate () {
	BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
	if [ -z $BRANCH_NAME ] || [ "$BRANCH_NAME" == "HEAD" ] || [ "$SKIP_PREPARE_COMMIT_MSG" == 1 ]; then
		exit
	fi
}

addTicket() {
	TICKET=$(git rev-parse --abbrev-ref HEAD 2>/dev/null | grep -E '[A-Z]{2,5}-[0-9]{1,6}' -o)
	DESCRIPTION=$(git config branch."$TICKET".description)
	echo "[$TICKET]: $(cat $COMMIT_EDITMSG)" > $COMMIT_EDITMSG
}

MERGE=$(cat $COMMIT_EDITMSG|grep -i 'merge'|wc -l)
if [ $MERGE -eq 0 ] ; then
	validate;
	addTicket;
fi
