version: "3.7"

services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    restart: always
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME='root'
#      - MONGO_INITDB_ROOT_PASSWORD='root'
#      - MONGO_INITDB_DATABASE='root-db'
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db'
#      - './init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro'
    #command: [--auth]

#  networks:
#    default:
#      external:
#        name: mongo-network

 # volumes:
 #   mongodbdata: